#!/bin/bash
echo "初期化中"
configfile="config.json"
if [ ! -e $configfile ]; then

	cat <<EOF >$configfile
{
	"\$schema": "./schema.json"
}
EOF

fi
cd packages/database

touch bot.db
bunx prisma db push

cd ../core
mkdir -p log
