#!/bin/bash
# 設定ファイルが存在しなければ生成する
configfile="config.json"
if [ ! -e $configfile ]; then

	cat <<EOF >$configfile
{
	"\$schema": "./schema.json"
}
EOF

	cd packages/database
	# データベースが存在しなければ作成する
	touch bot.db
	# データベースに対して内容をpushする
	bunx prisma db push

	cd ../core
	mkdir -p log

fi

# configファイルがあるなら多分初期化処理いらないよね大丈夫よね
