#!/bin/bash
cd packages/database
touch bot.db
bunx prisma migrate dev --name init
cd ../../
mkdir log
configfile="config.json"
if [ ! -e $configfile ]; then

	cat <<EOF >$configfile
{
	"\$schema": "./schema.json"
}
EOF

fi
